seq='MPEEGSGCSVRRRPYGCVLRAALVPLVAGLVICLVVCIQRFAQAQQQLPLESLGWDVAELQLNHTGPQQDPRLYWQGGPALGRSFLHGPELDKGQLRIHRDGIYMVHIQVTLAICSSTTASRHHPTTLAVGICSPASRSISLLRLSFHQGCTIASQRLTPLARGDTLCTNLTGTLLPSRNTDETFFGVQWVRP'

count=0
i=[]
for index,aa in enumerate(seq):
    if aa=='R' or aa=='L' or aa=='A' or aa=='N' or aa=='Q':
        count+=1
        i.append(index+1)
print(count,i)
